-- ProjNav VHDL simulation template: sec_func_sec_func_tb_vhd_tb.udo
-- You may edit this file after the line that starts with
-- '-- START' to customize your simulation
-- START user-defined simulation commands
