# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath C:/modeltech64_10.3b/win64
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/project_3/project_3.cache/wt [current_project]
set_property parent.project_path D:/project_3/project_3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  D:/project_3/project_3.srcs/sources_1/new/ALU_d.vhd
  D:/project_3/project_3.srcs/sources_1/new/7dd_d.vhd
  D:/project_3/project_3.srcs/sources_1/new/ALU_B_d.vhd
}
read_xdc D:/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files D:/Nexys4DDR_Master.xdc]

synth_design -top ALU_B_d -part xc7a100tcsg324-1
write_checkpoint -noxdef ALU_B_d.dcp
catch { report_utilization -file ALU_B_d_utilization_synth.rpt -pb ALU_B_d_utilization_synth.pb }
